bubbles/rentals/urls.py
###########################################################################
# Bubbles is Copyright (C) 2018 Kyle Robbertze <krobbertze@gmail.com>
#
# Bubbles is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 3 as
# published by the Free Software Foundation.
#
# Bubbles is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Bubbles. If not, see <http://www.gnu.org/licenses/>.
###########################################################################
"""bubbles URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/2.0/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.urls import path
from . import views

app_name = 'rentals'

urlpatterns = [
    path('', views.index, name='index'),
    path('request/', views.request_equipment, name='request_equipment'),
    path('request/<int:request_id>/', views.request_equipment,
         name='request_equipment'),
    path('rent/', views.rent_equipment, name='rent_equipment'),
    path('rent/<int:rental_request>/', views.rent_equipment, name='rent_equipment'),
    path('rent/<int:rental_request>/save/', views.save_rental_request, name='save_rental_request'),
    path('return/<int:rental_id>/', views.return_equipment, name='return_equipment'),
    path('admin/admin_log/', views.view_admin_log, name='view_admin_log'),
]

bubbles/urls.py
###########################################################################
# Bubbles is Copyright (C) 2018 Kyle Robbertze <krobbertze@gmail.com>
#
# Bubbles is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 3 as
# published by the Free Software Foundation.
#
# Bubbles is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Bubbles. If not, see <http://www.gnu.org/licenses/>.
###########################################################################
"""bubbles URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/2.0/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.urls import include, path

from .admin import admin_site

urlpatterns = [
    path('', include('bubbles.rentals.urls')),
    path('', include('django_prometheus.urls')),
    path('inventory/', include('bubbles.inventory.urls')),
    path('admin/', admin_site.urls),
    path('admin/reporting/', include('bubbles.reporting.urls')),
    path('accounts/', include('bubbles.registration.urls')),
    path('docs/', include('bubbles.pages.urls')),
    path('temp/', include('django.contrib.admindocs.urls')),
]

bubbles/rentals/models.py
###########################################################################
# Bubbles is Copyright (C) 2018 Kyle Robbertze <krobbertze@gmail.com>
#
# Bubbles is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 3 as
# published by the Free Software Foundation.
#
# Bubbles is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Bubbles. If not, see <http://www.gnu.org/licenses/>.
###########################################################################
import datetime

from django.conf import settings
from django.db import models
from bubbles.inventory.models import *
from django.utils.translation import gettext_lazy as _

class RentalPeriod(models.Model):
    start_date = models.DateField(_('Start date'))
    end_date = models.DateField(_('End date'), null=True)
    default_deposit = models.IntegerField(_('Deposit'))
    default_cost_per_item = models.IntegerField(_('Cost per item'))
    name = models.CharField(_('Name'), max_length=255)
    hidden = models.BooleanField(default=False)

    def __str__(self):
        if self.end_date:
            return '{} ({} - {})'.format(self.name,
                                          self.start_date,
                                          self.end_date)
        return '{} ({} -)'.format(self.name, self.start_date)

class Rental(models.Model):
    REQUESTED = 'REQ'
    RENTED = 'REN'
    RETURNED = 'RET'
    STATE_CHOICES = (
        (REQUESTED, _('Requested')),
        (RENTED, _('Rented')),
        (RETURNED, _('Returned')),
    )
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    approved_by = models.ForeignKey(settings.AUTH_USER_MODEL,
                                    on_delete=models.SET_NULL,
                                    limit_choices_to={'is_staff': True},
                                    related_name='approved_rentals_set',
                                    null=True, blank=True)
    state = models.CharField(_('State'),
                             max_length=3,
                             choices=STATE_CHOICES,
                             default=REQUESTED)
    deposit = models.IntegerField(_('Deposit'))
    notes = models.TextField(_('Notes'), null=True, blank=True)
    deposit_returned = models.BooleanField(_('Deposit returned'), default=True)
    rental_period = models.ForeignKey(RentalPeriod, on_delete=models.CASCADE)
    weight = models.IntegerField(_('Weight'), null=True, blank=True)

    class Meta:
        permissions = [
            ('free_rental', 'Can rent gear without paying'),
        ]

    def is_overdue(self):
        today = datetime.date.today()
        if self.rental_period.end_date:
            return self.rental_period.end_date < today
        else:
            return False

    def is_due(self):
        today = datetime.date.today()
        if self.rental_period.end_date:
            return self.rental_period.end_date == today
        else:
            return False

    def __str__(self):
        return 'Rental by {} for {}'.format(self.user, self.rental_period)

class RentalItem(models.Model):
    rental = models.ForeignKey(Rental, on_delete=models.CASCADE, null=True)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    cost = models.IntegerField(_('Cost'), default=0)
    returned = models.BooleanField(_('Returned'), default=False)

    def __str__(self):
        if self.rental:
            return '{} to {}'.format(self.item, self.rental.user)
        return '{} to unknown'.format(self.item)

    def __eq__(self, other):
        if isinstance(other, self.__class__):
            return self.pk == other.pk and self.returned == other.returned
        return False

    def __hash__(self):
        return self.pk ^ self.returned

class RequestItem(models.Model):
    rental = models.ForeignKey(Rental, on_delete=models.CASCADE, null=True)
    item_description = models.CharField(_('Type'), max_length=255)
    item_size = models.CharField(_('Size'), max_length=3, null=True, blank=True)
    cost = models.IntegerField(_('Cost'), default=0)
    item_number = models.CharField(_('Number'), max_length=5, null=True,
                                   blank=True)

    def __str__(self):
        if self.rental:
            return '{} to {}'.format(self.item_description, self.rental.user)
        return '{} to unknown'.format(self.item_description)

bubbles/rentals/templates/rentals/admin_log.html
{% extends "bubbles/base.html" %}

{% block content %}
<div class="row">
  <div class="col-sm-6">
    <div class="row">
      <h1>Recent Administration Actions</h1>
    </div>
    <div class="col-sm-12">
      {% load log %}
      {% if not admin_log %}
      <p>None available</p>
      {% else %}
      <ul class="list-group">
        {% for entry in admin_log %}
        <li class="list-group-item">
          <span class="fas fa-{% if entry.is_addition %}plus{% endif %}{% if entry.is_change %}pencil-alt{% endif %}{% if entry.is_deletion %}minus{% endif %}"></span>
          {% if entry.is_deletion or not entry.get_admin_url %}
          {{ entry.user }} - {{ entry.object_repr }}
          {% if entry.content_type %}
          - {% filter capfirst %}{{ entry.content_type }}{% endfilter %}
          {% else %}
          - Unknown content
          {% endif %}
          {% else %}
          <a href="{{ entry.get_admin_url }}">{{ entry.user }} - {{ entry.object_repr }}
            {% if entry.content_type %}
            - {% filter capfirst %}{{ entry.content_type }}{% endfilter %}
            {% else %}
            - Unknown content
            {% endif %}</a>
          {% endif %}
        </li>
        {% endfor %}
      </ul>
      {% endif %}
    </div>
  </div>
{% endblock %}

bubbles/rentals/templates/rentals/index.html
{% extends "bubbles/base.html" %}

{% block pre_content %}
{% block messages %}
{% if messages %}
{% for message in messages %}
<div class="alert alert-success altert-dismissible">
  <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
  {{ message|capfirst }}
</div>
{% endfor %}
{% endif %}
{% endblock messages %}
{% endblock %}

{% block content %}
<div class="row">
  {% if rentals %}
  <div class="col-sm-6">
    <h1>My Rentals</h1>
    <div class="table-responsive">
      <table class="table table-striped" id="rental-table">
        <thead>
          <tr>
            <th scope="col">Item</th>
            <th scope="col">Number</th>
          </tr>
        </thead>
        <tbody>
          {% for rentalitem in rentals %}
          <tr>
            <td>{{ rentalitem.item.description }}</td>
            <td>{{ rentalitem.item.number }}</td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
  {% endif %}
  {% if requests %}
  <div class="col-sm-6">
    <h1>My Requests</h1>
    <ul class="list-group">
      {% for request in requests %}
      <li class="list-group-item"><a href={% url 'rentals:request_equipment' request.id %}>{{ request.rental_period }}</a>
        {% endfor %}
  </div>
  {% endif %}
  {% if rentals and requests %}
</div>
<div class="row">
  {% endif %}
  <div class="col-sm-6">
    <iframe class="weather" width="650" height="450" src="https://embed.windy.com/embed2.html?lat=-34.247&lon=18.532&zoom=11&level=surface&overlay=waves&menu=&message=&marker=&calendar=now&pressure=&type=map&location=coordinates&detail=true&detailLat=-34.186&detailLon=18.443&metricWind=default&metricTemp=default&radarRange=-1" frameborder="0"></iframe> 
  </div>
</div>
{% endblock %}

bubbles/rentals/templates/rentals/rent_equipment.html
{% extends "bubbles/base.html" %}
{% load static %}

{% block extra_head %}
{{ block.super }}
{{ form.media }}
<script src="{% static 'js/save_button.js' %}"></script>
{% endblock %}

{% block pre_content %}
{% block messages %}
{% if messages %}
{% for message in messages %}
<div class="alert alert-success altert-dismissible">
  <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
  {{ message|capfirst }}
</div>
{% endfor %}
{% endif %}
{% endblock messages %}
{% endblock %}

{% block content %}
<div class="row">
  <div class="col-sm-10">
    <form action="{{ url }}" method="post" id="rental-form">
      {% csrf_token %}
      {% if rental_user %}
      <div class="form-group">
        <label class="control-label" for="id_user">User:</label>
        <p class="form-control-static" id="id_user">{{ rental_user.first_name }} {{ rental_user.last_name }} ({{ rental_user.username }})</p>
      </div>
      {% endif %}
      {% for field in form %}
      {% if field.field.widget.input_type == "checkbox" %}
      <div class="form-check">
      {% else %}
      <div class="form-group">
        {% endif %}
        {% if field.field.widget.input_type == "checkbox" %}
        {{ field }}
        <label class="control-label form-check-label" for="{{ field.id_for_label }}">{{ field.label }}:</label>
        {% else %}
        <label class="control-label" for="{{ field.id_for_label }}">{{ field.label }}:</label>
        {{ field }}
        {% endif %}
        {% for error in field.errors %}
        <div class="alert alert-danger" role="alert">
          {{ error }}
        </div>
        {% endfor %}
      </div>
      {% endfor %}
      <div class="form-group btn-group">
        <button class="btn btn-primary" id="submit-btn" type="submit">Rent</button>
        {% if show_save %}
        <button class="btn btn-secondary" id="save-btn" type="button">Save</button>
        {% endif %}
      </div>
      {% if show_cost %}
      <div class="form-group">
        <label class="control-label" for="id_total_cost">Total cost:</label>
        <p class="form-control-static" id="id_total_cost"></p>
      </div>
      {% endif %}
    </form>
  </div>
</div>
{% if show_save %}
<div id="save-target" class="hidden" hidden>
  {% url 'rentals:save_rental_request' request_id %}
</div>
{% endif %}
{% endblock %}

bubbles/rentals/templates/rentals/rental_confirmation.html
{% extends "bubbles/base.html" %}

{% block content %}
Equipment rented!
{% endblock %}

bubbles/rentals/templates/rentals/request_confirmation.html
{% extends "bubbles/base.html" %}

{% block content %}
Equipment requested!
{% endblock %}

bubbles/rentals/templates/rentals/return_confirmation.html
{% extends "bubbles/base.html" %}

{% block content %}
Equipment returned!
{% endblock %}